
[project]
description = ""
authors = [
    {name = "Samuel Murillo", email = "contact@samuelmurillo.xyz"},
]
dependencies = [
    "flask>=2.3.2",
    "hvac>=1.1.1",
]
requires-python = ">=3.11"
license = {text = "MIT"}
